version: "3.7"

services:
  cbbc:
    image: cbbc-image
    container_name: cbbc
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx-image
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - cbbc
    ports:
      - "80:80"
      - "3001:3001"
