version: '3.7'

services:
  cbbc:
    image: cbbc-image
    container_name: cbbc
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:1.17.9-alpine
    container_name: nginx-cbbc
    links:
      - cbbc
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '5000:80'
      - '3001:3001'
