version: '3.7'

services:
  cbbc_dev:
    image: cbbc
    container_name: cbbc-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - NODE_ENV=production
