# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  compose:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'fc:1e:24:c1:d7:34:e3:91:c2:0b:82:c8:c0:c1:d1:bf'
      - checkout
      - run:
          name: Add host
          command: echo "ec2-54-167-123-102.compute-1.amazonaws.com" >> ~/.ssh/known_hosts
      - run:
          name: Docker Compose on AWS
          command: docker-compose -H ssh://ubuntu@ec2-54-167-123-102.compute-1.amazonaws.com up -d --build --force-recreate

workflows:
  version: 2
  compose-master:
    jobs:
      - compose:
          filters:
            branches:
              only: master
